version: '3.9'

services:
  proyectospring:
    build: proyectospring
    ports:
      - "8080:8080"
    environment:
      BD_URL: jdbc:mysql://app_spring:3306/BD_SPRINGBOOT?createDatabaseIfNotExist=true&serverTimezone=UTC
      BD_USER: root
      BD_PASSWORD: 1234
    restart: always
    depends_on:
      app_spring:
          condition: service_healthy
  app_spring:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: BD_SPRINGBOOT
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10